#!/usr/bin/env python
#encoding: utf-8
import cmd
import sys

filtered_words_path = '/Users/calcifer/filtered_words.txt'

class CLI(cmd.Cmd):

	def __init__(self):

		cmd.Cmd.__init__(self)
		self.intro = 'Filtered words Detective'
		self.words = map(lamda i: i.strip('\n').decode('utf-8'), open(filtered_words_path).readlines())
		self.prompt = "> "

	def default(self, line):
		line = line.decode('utf-8')
		for i in self.words:
			line = line.replace(i, len(i)*'*')
		print line

	def do_quit(self, arg):
		exit()
		return True

if __name__ == '__main__':
	cli = CLI()
	cli.cmdloop()
